# Generated by Django 4.1 on 2022-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('autor', models.TextField(max_length=80)),
                ('descricao', models.TextField(max_length=200)),
                ('imagem', models.TextField()),
            ],
        ),
    ]
